# example netlify.toml
[build]
  command = "hugo"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.79.0"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

